#!/system/xbin/busybox sh

if [ "${SUBSYSTEM}" == "block" ] && [ `echo ${DEVPATH}|/system/xbin/busybox grep -c "s3c_otghcd"` -ge 1 ] ;
then
  mountdir="/mnt/sdcard/usbStorage"
  devbase=`/system/xbin/busybox basename ${DEVPATH}`
  if [ "${ACTION}" == "add" ];
  then
    /system/xbin/busybox mkdir -p ${mountdir}/${devbase}
    #/sbin/ntfs-3g /dev/block/platform/s3c_otghcd/${devbase} ${mountdir}/${devbase} -o ro || rmdir ${mountdir}/${devbase}
    /sbin/ntfs-3g /dev/block/platform/s3c_otghcd/${devbase} ${mountdir}/${devbase} -o ro
  fi
  if [ "${ACTION}" == "remove" ];
  then
    /system/xbin/busybox umount -f ${mountdir}/${devbase}
    #rmdir ${mountdir}/${devbase}
  fi
fi
